query Entry($uri: [String], $siteId: [QueryArgument]) {
    entry (uri: $uri, siteId: $siteId) {
        id
        slug
        title
        ... on auxiliary_auxiliary_Entry {
            headingPlain
        }
    }
}