# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'  

jobs:
  
  build:
    name: Deployment
    runs-on: [self-hosted, Production]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build
    - run: npm run start