# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment to DigitalOcean Droplet

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'  

jobs:
  
  build:
    name: Deployment
    
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repo files
      uses: actions/checkout@v2
    
    - name: Install and use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Running clean install & building nuxt
      run: npm ci
      
    - name: Building Nuxt app..
      run: npm run build
      
    - name: Create .env file
      run: |
        touch .env
        echo API_SECRET="this" >> .env
        cat .env
      
    - name: Package Files
      run: |
        mkdir ../
        cp -TR . ../
        tar -cvf deployment-files.tar ../

    - name: Deploy files to server
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.REMOTE_HOST }}
       username: ${{ secrets.REMOTE_USER }}
       key: ${{ secrets.SERVER_SSH_KEY }}
       rm: true
       source: "deploy.tar"
       target: "${{ secrets.REMOTE_TARGET }}"
