# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment to DigitalOcean Droplet

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'  

jobs:
  
  build:
    name: Deployment
    
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repo files
      uses: actions/checkout@v2
    
    - name: Install and use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Running clean install
      run: npm ci

    - name: Deploy files to server
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.REMOTE_HOST }}
       username: ${{ secrets.REMOTE_USER }}
       key: ${{ secrets.SERVER_SSH_KEY }}
       rm: true
       source: ".nuxt"
       target: "${{ secrets.REMOTE_TARGET }}"